<div class="pagination" style="width:100%; margin-top: 10px;">
    <div style="float:left;width:28%">
    </div>
    <div style="float:right;width:70%;">
        <!-- First page link -->
        <?php if (isset($this->previous)): ?>
             <a href="<?= $this->url(array('page' => $this->first)); ?>">&lt;&lt;Prima Pagina</a>
        <?php else: ?>
                <span class="disabled">&lt;&lt;Prima Pagina</span> |
        <?php endif; ?>
    
        <!-- Previous page link -->
    
        <?php if (isset($this->previous)): ?>
              <a href="<?= $this->url(array('page' => $this->previous)); ?>">&lt; Inapoi</a> |
        <?php else: ?>
            <span class="disabled">&lt; Inapoi</span> |
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a>
            <?php else: ?>
                <?= $page; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
              | <a href="<?= $this->url(array('page' => $this->next)); ?>">Urmatoarea &gt;</a> |
        <?php else: ?>
            | <span class="disabled">Urmatoarea &gt;</span> |
        <?php endif; ?>
        <!-- Last page link -->
        <?php if (isset($this->next)): ?>
              <a href="<?= $this->url(array('page' => $this->last)); ?>">Ultima Pagina>></a>
        <?php else: ?>
            <span class="disabled">Ultima Pagina</span>
        <?php endif; ?>
        &nbsp;  <?php  // echo $this->current; ?>  <?php //echo $this->last; ?>
    </div>
 </div>