<div id="welcome">
    <div class="holder">
        <p id="piese-auto">Asistenta:</p>
            <div class="dbl-bg">
                <div style="text-align: justify"><img style="display: inline; float: left; margin-right: 5px; margin-left: 10px; margin-top: -10px;" align="right" src="http://www.markify.com/images/ctm/originals/007048911.JPG" width="200" height="200" /></div>
                <div style="text-align: justify"><font color="#666666">
                    ATP Exodus team is always at your disposal <br>
                    
              </font></div> 
              
              <div style="text-align: justify">&#160;</div>
    </div>
    <script type="text/javascript">
  $( document ).tooltip({
    position: {
//      my: 'top center',
//      at: 'top+15 center'
    }
  });
</script>
